'use strict';

const companies = [
  {
    name: 'backblaze',
    color: 'red',
    option: false,
    minPayment: 7,
    maxPayment: null,
    storagePrice1: 0.005,
    storageFree1: 0,
    storagePrice2: 0.005,
    storageFree2: 0,
    transferPrice1: 0.01,
    transferFree1: 0,
    transferPrice2: 0.01,
    transferFree2: 0,
  },
  {
    name: 'bunny',
    color: 'orange',
    option: false,
    minPayment: 0,
    maxPayment: 10,
    storagePrice1: 0.01,
    storageFree1: 0,
    storagePrice2: 0.02,
    storageFree2: 0,
    transferPrice1: 0.01,
    transferFree1: 0,
    transferPrice2: 0.01,
    transferFree2: 0,
  },
  {
    name: 'scaleway',
    color: 'purple',
    option: true,
    minPayment: 0,
    maxPayment: null,
    storagePrice1: 0.06,
    storageFree1: 75,
    storagePrice2: 0.03,
    storageFree2: 75,
    transferPrice1: 0.02,
    transferFree1: 75,
    transferPrice2: 0.02,
    transferFree2: 75,
  },
  {
    name: 'vultr',
    color: 'blue',
    option: false,
    minPayment: 5,
    maxPayment: null,
    storagePrice1: 0.01,
    storageFree1: 0,
    storagePrice2: 0.01,
    storageFree2: 0,
    transferPrice1: 0.01,
    transferFree1: 0,
    transferPrice2: 0.01,
    transferFree2: 0,
  },
];

export default companies;